name: Pull Request Tests

on: pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          # ignore line too long errors
          args: --ignore E501
